name: release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Install Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Test
        run: go test ./...

      - name: Build binary
        run: |
          mkdir -p bin
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -trimpath -o bin/trellis-proxy-sync .

      - name: Package binary
        run: tar -czf trellis-proxy-sync_linux_x64.tar.gz -C bin trellis-proxy-sync

      - name: Create release
        uses: softprops/action-gh-release@da05d552573ad5aba039eaac05058a918a7bf631
        with:
          files: |
            trellis-proxy-sync_linux_x64.tar.gz
          generate_release_notes: true
